name: Create release
run-name: ${{ inputs.publish == 'true' && '' || 'Draft' }} Release created for ${{ inputs.chart }}:${{ inputs.version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      chart:
        type: choice
        description: Chart to release
        required: true
        default: test-chart
        options:
          - test-chart
      version:
        type: string
        description: Chart version to release
        required: true
      publish:
        type: boolean
        description: Publish the release or just draft it
        required: false
        default: true

permissions:
  contents: write
  pull-requests: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update chart version
        uses: mikefarah/yq@master
        env:
          VERSION: ${{ inputs.version }}
        with:
          cmd: yq e -i '.version = env(VERSION)' ./charts/${{ inputs.chart }}/Chart.yaml

      - name: Commit chart version update
        id: commit
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          git diff
          git commit -am "Update chart ${{ inputs.chart }} version to ${{ inputs.version }}"
          git push

          update_commit=$(git rev-parse HEAD)
          echo "commit_sha1=${update_commit}" >> "${GITHUB_OUTPUT}"

      - name: ${{ inputs.chart }} Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: "release-drafter/${{ inputs.chart }}.yaml"
          publish: false
          version: ${{ inputs.version }}
          name: "${{ inputs.chart }}-${{ inputs.version }}"
          tag: "${{ inputs.chart }}-${{ inputs.version }}"
          latest: true
          commitish: ${{ steps.commit.outputs.commit_sha1 }}
          token: ${{ secrets.GITHUB_TOKEN }}

  chart-release:
    if: ${{ inputs.publish }}
    uses: ./.github/workflows/release.yaml
    secrets: inherit
    needs: [github-release]
