name: Create release
run-name: Create release ${{ inputs.chart }}:${{ inputs.version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      chart:
        type: choice
        description: Chart to release
        required: true
        default: test-chart
        options:
          - test-chart
      version:
        type: string
        description: Chart version to release
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: "${{ inputs.chart }}-${{ inputs.version }}"
      RELEASE_TAG: "${{ inputs.chart }}-${{ inputs.version }}"
      CHART_DIR: "./main/charts/${{ inputs.chart }}"
      HELM_REPO_PUBLIC_URL: "https://musical-adventure-wo4898k.pages.github.io/"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: "main"
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.10.1"

      - name: Update chart version
        uses: mikefarah/yq@master
        env:
          VERSION: ${{ inputs.version }}
        with:
          cmd: yq e -i '.version = env(VERSION)' ${{ env.CHART_DIR }}/Chart.yaml

      - name: Commit chart version update
        id: commit
        working-directory: main
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          git diff
          git commit -am "Update chart ${{ inputs.chart }} version to ${{ inputs.version }}"
          git push

          update_commit=$(git rev-parse HEAD)
          echo "commit_sha1=${update_commit}" >> "${GITHUB_OUTPUT}"

      - name: Package chart ${{ inputs.chart }}
        id: package
        run: |
          id
          docker run \
            --user "${UID}:${GID}" \
            --workdir /chart \
            -v ${{ env.CHART_DIR }}:/chart \
            quay.io/helmpack/chart-releaser \
            package /chart --package-path .cr-release-packages

          echo "package_file=${{ env.CHART_DIR }}/.cr-release-packages/${{ inputs.chart }}-${{ inputs.version }}.tgz" >> "${GITHUB_OUTPUT}"

      - name: Create github release ${{ env.RELEASE_NAME }}
        id: release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: "release-drafter/${{ inputs.chart }}.yaml"
          publish: true
          version: ${{ inputs.version }}
          name: "${{ env.RELEASE_NAME }}"
          tag: "${{ env.RELEASE_TAG }}"
          latest: true
          commitish: ${{ steps.commit.outputs.commit_sha1 }}

      - name: Upload package chart to release
        id: upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ env.GITHUB_TOKEN }}
          file: ${{ steps.package.outputs.package_file }}
          tag: ${{ steps.release.outputs.tag_name }}

      - name: Update helm index
        working-directory: main
        run: |
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")

          echo "$owner"
          echo "$repo"
          ls -al ./charts/${{ inputs.chart }}/.cr-release-packages

          mkdir -p .cr-index

          docker run \
            --user "${UID}:${GID}" \
            --workdir /workdir \
            -v $(pwd):/workdir \
            quay.io/helmpack/chart-releaser \
            index --push -r "$repo" -o "$owner" --pages-branch gh-pages  --pages-index-path index.yaml --package-path ./charts/${{ inputs.chart }}/.cr-release-packages --token ${{ env.GITHUB_TOKEN }}

      # - name: Checkout gh-pages
      #   uses: actions/checkout@v3
      #   with:
      #     path: "pages"
      #     ref: "gh-pages"
      #     fetch-depth: 0

      # - name: Update helm index
      #   working-directory: pages
      #   run: |
      #     owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
      #     repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
      #     docker run \
      #       --user "${UID}:${GID}" \
      #       --workdir /workdir \
      #       -v $(pwd)/..:/workdir \
      #       quay.io/helmpack/chart-releaser \
      #       index -i ./index.yaml -r "$repo" -o "$owner" --package-path ../${{ env.CHART_DIR }}/.cr-release-packages --token ${{ env.GITHUB_TOKEN }}

      #     cat index.yaml

      # - name: Push index
      #   working-directory: pages
      #   run: |
      #     git config user.name "$GITHUB_ACTOR"
      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      #     git diff
      #     git add index.yaml
      #     git commit -m "Updated from ref: $GITHUB_SHA"
      #     git push
