name: Chart testing

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test chart Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: "release-drafter/test-chart.yaml"
          publish: false
          token: ${{ secrets.GITHUB_TOKEN }}
